### ISSUE TITLE
Port to Python 3

### ISSUE THREAD

**Issue by ratulotron** [Antrikshy/ignr.py#3]

**Comment by ssantana92** [comment]
I have ported this to Python 3 and created a pull request. 

Meanwhile, you may want to try using my fork: https://github.com/ssantana92/ignr.py

**Comment by ghisvail** [comment]
Closed by #4?

**Comment by Antrikshy** [comment]
I wasn't sure why @ssantana92 closed the PR immediately, and forgot to ask.

**Comment by espoelstra** [comment]
It might be worth using `futurize` from `pip install future` to implement 3.x syntax with 2.7 backwards compatibility so that after the deprecation of 2.7 in 2020 you don't really need to change anything but can clean up the backwards compatibility someday.

**Comment by Antrikshy** [comment]
Yeah, now that we have EOL date, I’ll stop being lazy and actually get on this using one of the solutions out there. Good to know people use this tool!

**Comment by Antrikshy** [comment]
Done! After much delay, I present to you, v2.0. This drops Python 2 support, as I figured it wasn't worth the effort, and because I prefer keeping dependencies clean in simple projects like this one. I also had to make some compatibility updates, like adding HTTP headers in my requests to gitignore.io, which may mean the previous version has been broken for some time.
